<?php

namespace App\Services;

use Doku\Snap\Snap;
use App\Models\PaymentGatewayConfig;

class DokuService
{
    protected $snap;
    protected $config;
    
    public function __construct(PaymentGatewayConfig $config)
    {
        $this->config = $config;
        
        // Initialize DOKU Snap with configuration
        // Based on README: new Snap(privateKey, publicKey, dokuPublicKey, clientId, issuer, isProduction, secretKey, authCode)
        // Note: authCode is optional parameter (8th parameter)
        $this->snap = new Snap(
            $config->decrypted_private_key ?? '',  // privateKey - Required for signature
            $config->public_key ?? '',              // publicKey - Required
            $config->doku_public_key ?? '',         // dokuPublicKey - Required
            $config->client_id,                     // clientId - Required
            $config->issuer ?? '',                  // issuer - Optional
            $config->isProduction(),                // isProduction - Required (boolean)
            $config->decrypted_secret_key ?? '',    // secretKey - Required
            $config->decrypted_auth_code ?? ''      // authCode - Optional (8th parameter)
        );
    }
    
    /**
     * Get Snap instance
     */
    public function getSnap()
    {
        return $this->snap;
    }
    
    /**
     * Get Token B2B for API requests
     */
    public function getTokenB2B(): string
    {
        $tokenResponse = $this->snap->getB2BToken();
        return $tokenResponse->accessToken ?? '';
    }
    
    /**
     * Test connection to DOKU API
     */
    public function testConnection()
    {
        try {
            // Simple test: validate token B2B
            // This will test if credentials are valid
            $tokenResponse = $this->snap->getB2BToken();
            
            // DOKU Success Response Codes start with "2" (2007300 = Successful)
            // Error Response Codes start with "4" or "5" (4017300 = Unauthorized, 5007300 = Server Error)
            $responseCode = $tokenResponse->responseCode ?? '';
            
            // Check if successful (code starts with "2" or empty, and has accessToken)
            if ((empty($responseCode) || str_starts_with($responseCode, '2')) && !empty($tokenResponse->accessToken)) {
                return [
                    'success' => true,
                    'message' => 'Koneksi ke DOKU API berhasil! Credentials valid.',
                    'environment' => $this->config->environment,
                    'token_expires_in' => $tokenResponse->expiresIn . ' seconds',
                    'response_code' => $responseCode,
                ];
            }
            
            // Token request failed
            return [
                'success' => false,
                'message' => 'Gagal mendapatkan token dari DOKU API.',
                'error_code' => $responseCode ?: 'unknown',
                'error_message' => $tokenResponse->responseMessage ?? 'Unknown error',
            ];
            
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => 'Error: ' . $e->getMessage(),
            ];
        }
    }
    
    /**
     * Create Virtual Account
     */
    public function createVirtualAccount($data)
    {
        // Get API endpoint URL
        $baseUrl = $this->config->isProduction() 
            ? 'https://api.doku.com' 
            : 'https://api-sandbox.doku.com';
        $endpoint = '/virtual-accounts/bi-snap-va/v1.1/transfer-va/create-va';
        $fullUrl = $baseUrl . $endpoint;

        // Log request details
        \Log::channel('va')->info('=== DOKU API HTTP Request ===', [
            'method' => 'POST',
            'url' => $fullUrl,
            'environment' => $this->config->environment,
            'client_id' => $this->config->client_id,
        ]);

        // Get B2B token for headers
        try {
            $tokenResponse = $this->snap->getB2BToken();
            $accessToken = $tokenResponse->accessToken ?? null;

            // Prepare headers (simulated based on DOKU documentation)
            $timestamp = now()->format('Y-m-d\TH:i:sP');
            
            $headers = [
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer ' . $accessToken,
                'X-TIMESTAMP' => $timestamp,
                'X-SIGNATURE' => '[Generated by DOKU SDK]',
                'X-PARTNER-ID' => $this->config->client_id,
                'X-EXTERNAL-ID' => uniqid('ext_', true),
                'CHANNEL-ID' => 'H2H',
            ];

            \Log::channel('va')->info('Request Headers', [
                'headers' => $headers,
            ]);

            // Convert DTO to array for logging
            $payload = [
                'partnerServiceId' => $data->partnerServiceId ?? null,
                'customerNo' => $data->customerNo ?? null,
                'virtualAccountNo' => $data->virtualAccountNo ?? null,
                'virtualAccountName' => $data->virtualAccountName ?? null,
                'virtualAccountEmail' => $data->virtualAccountEmail ?? null,
                'virtualAccountPhone' => $data->virtualAccountPhone ?? null,
                'trxId' => $data->trxId ?? null,
                'totalAmount' => [
                    'value' => $data->totalAmount->value ?? null,
                    'currency' => $data->totalAmount->currency ?? null,
                ],
                'additionalInfo' => [
                    'channel' => $data->additionalInfo->channel ?? null,
                    'virtualAccountConfig' => [
                        'reusableStatus' => $data->additionalInfo->virtualAccountConfig->reusableStatus ?? null,
                        'minAmount' => $data->additionalInfo->virtualAccountConfig->minAmount ?? null,
                        'maxAmount' => $data->additionalInfo->virtualAccountConfig->maxAmount ?? null,
                    ],
                ],
                'virtualAccountTrxType' => $data->virtualAccountTrxType ?? null,
                'expiredDate' => $data->expiredDate ?? null,
            ];

            \Log::channel('va')->info('Request Payload (Body)', [
                'payload' => $payload,
            ]);

        } catch (\Exception $e) {
            \Log::channel('va')->error('Failed to prepare request logging', [
                'error' => $e->getMessage(),
            ]);
        }

        // Call DOKU API
        $startTime = microtime(true);
        
        try {
            $response = $this->snap->createVa($data);
            $duration = round((microtime(true) - $startTime) * 1000, 2);

            \Log::channel('va')->info('=== DOKU API HTTP Response ===', [
                'duration_ms' => $duration,
                'response' => json_decode(json_encode($response), true),
            ]);

            return $response;
            
        } catch (\Exception $e) {
            $duration = round((microtime(true) - $startTime) * 1000, 2);
            
            \Log::channel('va')->error('=== DOKU API HTTP Error ===', [
                'duration_ms' => $duration,
                'error_message' => $e->getMessage(),
                'error_code' => $e->getCode(),
                'error_trace' => $e->getTraceAsString(),
            ]);

            throw $e;
        }
    }
    
    /**
     * Update Virtual Account
     */
    public function updateVirtualAccount($data)
    {
        return $this->snap->updateVa($data);
    }
    
    /**
     * Delete Virtual Account
     */
    public function deleteVirtualAccount($data)
    {
        return $this->snap->deletePaymentCode($data);
    }
    
    /**
     * Check Virtual Account Status
     */
    public function checkVirtualAccountStatus($data)
    {
        return $this->snap->checkStatusVa($data);
    }
    
    /**
     * Do Payment
     */
    public function doPayment($data, $authCode, $ipAddress)
    {
        return $this->snap->doPayment($data, $authCode, $ipAddress);
    }
    
    /**
     * Do Payment Jump App
     */
    public function doPaymentJumpApp($data, $deviceId, $ipAddress)
    {
        return $this->snap->doPaymentJumpApp($data, $deviceId, $ipAddress);
    }
    
    /**
     * Check Transaction Status
     */
    public function checkStatus($data)
    {
        return $this->snap->doCheckStatus($data);
    }
    
    /**
     * Do Refund
     */
    public function doRefund($data, $authCode, $ipAddress, $deviceId)
    {
        return $this->snap->doRefund($data, $authCode, $ipAddress, $deviceId);
    }
    
    /**
     * Balance Inquiry
     */
    public function balanceInquiry($data, $authCode, $ipAddress)
    {
        return $this->snap->doBalanceInquiry($data, $authCode, $ipAddress);
    }
    
    /**
     * Account Binding
     */
    public function accountBinding($data, $ipAddress, $deviceId)
    {
        return $this->snap->doAccountBinding($data, $ipAddress, $deviceId);
    }
    
    /**
     * Account Unbinding
     */
    public function accountUnbinding($data, $ipAddress)
    {
        return $this->snap->doAccountUnbinding($data, $ipAddress);
    }
    
    /**
     * Card Registration
     */
    public function cardRegistration($data)
    {
        return $this->snap->doCardRegistration($data);
    }
    
    /**
     * Card Unbinding
     */
    public function cardUnbinding($data)
    {
        return $this->snap->doCardUnbinding($data);
    }
    
    /**
     * Get Token B2B2C
     */
    public function getTokenB2B2C($authCode)
    {
        return $this->snap->getTokenB2B2C($authCode);
    }
    
    /**
     * Validate Token B2B
     */
    public function validateTokenB2B($authorization)
    {
        return $this->snap->validateTokenB2B($authorization);
    }
}
